# Generated by Django 2.0.2 on 2018-02-08 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=500)),
                ('song_logo', models.CharField(max_length=1000)),
                ('song_date_release', models.DateField(default=datetime.date.today, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='album_date_release',
            field=models.DateField(default=datetime.date.today, max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
    ]
